// <auto-generated />
namespace ISB_Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DbEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201909091509476_DbEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
